In [1]:
!pip install nbformat

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)

In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

df = sns.load_dataset('planets')
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [57]:
df.shape

(1035, 6)

In [58]:
df.dropna(inplace=True)
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [59]:
# Constructing a new feature 'mass_per_distance' from mass and distance
df['mass_per_distance'] = df['mass'] / df['distance']
df.head()

,method,number,orbital_period,mass,distance,year,mass_per_distance
0,Radial Velocity,1,269.300,7.10,77.40,2006,0.091731
1,Radial Velocity,1,874.774,2.21,56.95,2008,0.038806
2,Radial Velocity,1,763.000,2.60,19.84,2011,0.131048
3,Radial Velocity,1,326.030,19.40,110.62,2007,0.175375
4,Radial Velocity,1,516.220,10.50,119.47,2009,0.087888

In [60]:
# Categorize orbital period into short, medium, long
def period_type(val):
    if val <= 10:
        return 0   # short period
    elif val > 10 and val <= 100:
        return 1   # medium period
    else:
        return 2   # long period

df['period_type'] = df['orbital_period'].apply(period_type)
df.head()

,method,number,orbital_period,mass,distance,year,mass_per_distance,period_type
0,Radial Velocity,1,269.300,7.10,77.40,2006,0.091731,2
1,Radial Velocity,1,874.774,2.21,56.95,2008,0.038806,2
2,Radial Velocity,1,763.000,2.60,19.84,2011,0.131048,2
3,Radial Velocity,1,326.030,19.40,110.62,2007,0.175375,2
4,Radial Velocity,1,516.220,10.50,119.47,2009,0.087888,2

In [61]:
df['period_type'].value_counts()

period_type
2    334
1     96
0     68
Name: count, dtype: int64

In [62]:
df.drop(columns=['orbital_period', 'mass', 'distance'], inplace=True)
df.head()

            method  number  year  mass_per_distance  period_type
0  Radial Velocity       1  2006           0.091731            2
1  Radial Velocity       1  2008           0.038806            2
2  Radial Velocity       1  2011           0.131048            2
3  Radial Velocity       1  2007           0.175375            2
4  Radial Velocity       1  2009           0.087888            2

In [65]:
# Look at method column
df['method'].value_counts()

method
Radial Velocity    497
Transit              1
Name: count, dtype: int64

In [66]:
# EASY SPLIT 1 - Just create binary column
# Is it Transit method? Yes=1 No=0
df['is_transit'] = (df['method'] == 'Transit').astype(int)
df[['method', 'is_transit']].head(10)

             method  is_transit
0   Radial Velocity           0
1   Radial Velocity           0
2   Radial Velocity           0
3   Radial Velocity           0
4   Radial Velocity           0
5   Radial Velocity           0
6   Radial Velocity           0
8   Radial Velocity           0
9   Radial Velocity           0
10  Radial Velocity           0