daa analysis a a process of cleaning,tranforming and modelling data with goal of discovering usefull information,conclution that supprt decision making

### 📌 Importance of **Pandas** in Python (Simple Explanation)

**pandas** is one of the most important libraries in Python for working with data.

Since you are learning Python and doing AI/ML projects, Pandas is **very useful** for you.

---

## 🌟 1. Easy to Work with Data

Pandas helps you:

* Read data from CSV files
* Read Excel files
* Work with tables
* Handle large datasets easily

Example:

```python
import pandas as pd

df = pd.read_csv("data.csv")
print(df.head())
```

It shows data in **table format** (rows and columns).

---

## 🌟 2. Data Cleaning (Very Important for AI/ML)

Real-world data is messy 😅
Pandas helps you:

* Remove missing values
* Fill empty values
* Remove duplicates
* Rename columns
* Filter data

Example:

```python
df.dropna()     # remove missing values
df.fillna(0)    # replace missing with 0
```

For your **leaf disease CNN project**, cleaning data is very important before training.

---

## 🌟 3. Data Analysis

You can:

* Calculate mean, sum, max, min
* Count values
* Group data
* Sort data

Example:

```python
df["Age"].mean()
df["Marks"].max()
```

---

## 🌟 4. Fast and Efficient

Pandas works faster than normal Python lists when handling big data.

It is built on **NumPy**, so it is very powerful.

---

## 🌟 5. Used in Data Science & AI

Almost every Data Scientist uses Pandas with:

* **NumPy**
* **Matplotlib**
* **Scikit-learn**
* **TensorFlow**

So if you want to become strong in AI/ML, Pandas is must.

---

## 🌟 6. DataFrame (Main Power)

Pandas has something called **DataFrame**.

DataFrame = Table (like Excel sheet)

Example:

| Name | Age | Marks |
| ---- | --- | ----- |
| A    | 20  | 80    |
| B    | 21  | 90    |

This makes data easy to understand and manage.

---

# 🔥 In Simple Words

Pandas is important because:

✔ It helps read data
✔ It helps clean data
✔ It helps analyze data
✔ It saves time
✔ It is used in AI, ML, Data Science

---

## 📊 Data Structures in **pandas**

Pandas has **2 main data structures**:

### 1️⃣ Series

* 1D (one column)
* Like a list with index
* 👉 **Index + Values**

### 2️⃣ DataFrame

* 2D (table)
* Rows + Columns
* Collection of many Series

### 3️⃣ Index

* Row labels (0,1,2…)

---

### 💡 Super Simple:

* **Series** = One column
* **DataFrame** = Full table
* **Index** = Row number/name

In [2]:
import pandas as pd
x=[1,2,3]
v=pd.Series(x)
print(v)
print(type(v))

0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
print(v[2])

3

In [4]:
v=pd.Series(x,index=['a','b','c'],dtype='float')
print(v)

a    1.0
b    2.0
c    3.0
dtype: float64

In [7]:
disc={
    "name":['phython','c++','c','java'],
    "year":[1,2,3,4],
    "rank":['a','b','c','d'],

}
var=pd.Series(disc)
print(var)
print(type(var))

name    [phython, c++, c, java]
year               [1, 2, 3, 4]
rank               [a, b, c, d]
dtype: object
<class 'pandas.core.series.Series'>

In [8]:
s=pd.Series(12)
print(s)
print(type(s))

0    12
dtype: int64
<class 'pandas.core.series.Series'>

In [9]:
p=pd.Series(12,index=[1,2,3,4,5,6])
print(p)

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64

In [10]:
p=pd.Series(12,index=[1,2,3,4,5,6])
q=pd.Series(13,index=[1,2,3,4,5,6])
print(p+q)

1    25
2    25
3    25
4    25
5    25
6    25
dtype: int64

data structue :: dataframe

In [54]:
p=pd.DataFrame()
print(p)

Empty DataFrame
Columns: []
Index: []

In [75]:
import pandas as pd
d={
    "a":[1,2,3],
    "b":[1,2,3]

    }
df=pd.DataFrame(d)
df

   a  b
0  1  1
1  2  2
2  3  3

In [76]:
df['c'] = df['a'] + df['b']
df

   a  b  c
0  1  1  2
1  2  2  4
2  3  3  6

In [77]:
df['d']=df['c']%2==0
df

   a  b  c     d
0  1  1  2  True
1  2  2  4  True
2  3  3  6  True

inseartion operation in dataframe

In [78]:
df.insert(1,'new',df['a'])
df

   a  new  b  c     d
0  1    1  1  2  True
1  2    2  2  4  True
2  3    3  3  6  True

In [79]:
df['e']=df['a'][::]
df

   a  new  b  c     d  e
0  1    1  1  2  True  1
1  2    2  2  4  True  2
2  3    3  3  6  True  3

In [80]:
df['e']=df['a'][::1]
df

   a  new  b  c     d  e
0  1    1  1  2  True  1
1  2    2  2  4  True  2
2  3    3  3  6  True  3

In [81]:
df['e']=df['a'][::2]
df

   a  new  b  c     d    e
0  1    1  1  2  True  1.0
1  2    2  2  4  True  NaN
2  3    3  3  6  True  3.0

In [82]:
df['e']=df['a'][::3]
df

   a  new  b  c     d    e
0  1    1  1  2  True  1.0
1  2    2  2  4  True  NaN
2  3    3  3  6  True  NaN

deleting in dataframe

In [83]:
df1=df.pop("a")
df1

0    1
1    2
2    3
Name: a, dtype: int64

In [84]:
df

   new  b  c     d    e
0    1  1  2  True  1.0
1    2  2  4  True  NaN
2    3  3  6  True  NaN

In [85]:
del df["b"]
df

   new  c     d    e
0    1  2  True  1.0
1    2  4  True  NaN
2    3  6  True  NaN


🔹 What does df.pop('e') do?
It removes column 'e' from the DataFrame.

It returns that column as a Series.

In [ ]:

data = {
    "Name": ["Asha", "Ravi", "Priya", "Karan"],
    "Marks": [85, 90, 78, 92],
    "City": ["Nagpur", "Mumbai", "Delhi", "Pune"]
}

df = pd.DataFrame(data)

print(df)

    Name  Marks    City
0   Asha     85  Nagpur
1   Ravi     90  Mumbai
2  Priya     78   Delhi
3  Karan     92    Pune

In [ ]:
df["Name"]

0     Asha
1     Ravi
2    Priya
3    Karan
Name: Name, dtype: object

In [ ]:
df[["Name", "Marks"]]

    Name  Marks
0   Asha     85
1   Ravi     90
2  Priya     78
3  Karan     92

csv(comma seprated values)

In [ ]:
print(df.loc[0])

Name       Asha
Marks        85
City     Nagpur
Pass       True
Name: 0, dtype: object

In [ ]:
df[df["Marks"] > 80]

    Name  Marks    City
0   Asha     85  Nagpur
1   Ravi     90  Mumbai
3  Karan     92    Pune

In [ ]:
df["Pass"] = df["Marks"] > 80
print(df)

    Name  Marks    City   Pass
0   Asha     85  Nagpur   True
1   Ravi     90  Mumbai   True
2  Priya     78   Delhi  False
3  Karan     92    Pune   True

In [ ]:
print(df["Marks"].max())
print(df["Marks"].min())
print(df["Marks"].sum())

92
78
345

In [ ]:

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [ ]:
import pandas as pd
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    380
day3    390
dtype: int64

write csv

In [86]:
import pandas as pd
dis={
    "a":[1,2,3],
    "b":[11,22,33],
    "c":['a','b','c']

}
d=pd.DataFrame(dis)
d.to_csv("data.csv")


wayb to load the csv file into colab

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Titanic-Dataset.csv to Titanic-Dataset.csv

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [98]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [136]:
file_path='/content/drive/MyDrive/dataset/Titanic-Dataset.csv'

In [137]:
df=pd.read_csv(file_path)

In [138]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [104]:
df.tail(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [106]:
df.Embarked

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [107]:
df.size

10692

In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [114]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       882, 883, 884, 885, 886, 887, 888, 889, 890, 891],
      dtype='int64', name='PassengerId', length=891)

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [121]:
df[1:10:5]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [127]:
df[0:20:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.70,G6,S

dropna and fillna

In [130]:
df.dropna()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...
872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [132]:
df.shape

(891, 11)

In [133]:
df.dropna(axis=1)

,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
PassengerId,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [135]:
df.fillna(130, inplace = True)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df[df["Survived"] == 1].tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C

In [ ]:
df[df["Sex"] == "female"].head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [134]:
df.fillna(130, inplace = True)

   Unnamed: 0  a   b  c
0           0  1  11  a
1           1  2  22  b
2           2  3  33  c

In [ ]:
df.fillna({"Calories": 130}, inplace=True)

In [ ]:
df[df["Age"] > 30].head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
df.groupby("Pclass")["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [ ]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
df.sort_values("Age").tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df.sort_values("Fare", ascending=False).head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,C

In [ ]:
df.sort_values("Fare", ascending=False).tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,S

In [ ]:
df.drop("Cabin", axis=1, inplace=True)#make chage directly to og dataset

In [ ]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [139]:
!pip install nbformat

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)